Updated documentation formatting.
MDK-Packs/IoT_Socket pull request #1
Opened 2021-12-13 10:19 UTC by vovamarch

Use doxygen 1.9.x to verify documentation build locally.

2021-12-13 10:21 UTC, vovamarch commented
Actually only the last commit is relevant, so hope  you can merge without the history for others. Otherwise I can try to create a proper PR.

2021-12-22 12:59 UTC, RobertRostohar requested changes
In general looks ok but some files seem to be missing:
error: Extra file './Doxygen_Templates/tab_b.png' specified in HTML_EXTRA_FILES does not exist!
error: Extra file './Doxygen_Templates/navtree.js' specified in HTML_EXTRA_FILES does not exist!

2021-12-22 12:59 UTC, RobertRostohar commented on documentation/IoT_Socket.dxy
> +                         ./Doxygen_Templates/tab_b.png \
File "tab_b.png" is missing.

2021-12-22 12:59 UTC, RobertRostohar commented on documentation/IoT_Socket.dxy
> +                         ./Doxygen_Templates/navtree.js \
File "navtree.js" is missing.

2022-01-03 15:48 UTC, vovamarch commented on documentation/IoT_Socket.dxy
> +                         ./Doxygen_Templates/tab_b.png \
Added the missing file.

2022-01-03 15:48 UTC, vovamarch commented on documentation/IoT_Socket.dxy
> +                         ./Doxygen_Templates/navtree.js \
Added the missing file.

2022-01-04 07:43 UTC, RobertRostohar approved these changes
Looks good now.

2022-01-04 07:45 UTC, RobertRostohar commented
This PR has been rebased and merged into 'develop' branch (0984faf)

2022-01-04 07:45 UTC, closed without merging